title: "Pencil2D Animation"
tagline: "Open Source animation software"
description: "An easy, intuitive tool to make 2D hand-drawn animations."
show_downloads: true

#baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it unset if you don't need it.
#url: "https://www.pencil2d.org" # change this to the base hostname & protocol for your site

permalink: /:year/:month/:title.html

google_analytics: UA-5266256-7
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d %B, %Y"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-feed

theme: # leave it empty

# social
author: "The Pencil2D Team"
defaults:
  - values:
      image: /images/pencil_icon.png

twitter:
  username: pencil2d
facebook:
  publisher: 1379437495650288
  #app_id: 1798910940422432 # cayman-blog
  #admins:
github:
  owner_url: "https://github.com/pencil2d/pencil"
  owner_name: "pencil2d"

bitbucket:
  url: "https://bitbucket.org/chchwy/pencil2d"
